version: "3"

services:
  nginx:
    image: nginx
    links:
      - node
    ports:
      - "80:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  node:
    build:
      context: .
    ports: 
      - "3000:3000"
    links:
      - redis
    environment: 
      - REDIS_HOST:redis
    restart: always
  redis:
    image: redis
